import type { Theme } from "./registry";

const html = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Invoice {INVOICE_ID}</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Inter+Tight:wght@400&family=Inter:wght@400;500;600&display=swap" rel="stylesheet"><style>{CSS}</style></head><body><div class="invoice"><header class="header-section"><h1 class="invoice-title"><span>I</span><span>N</span><span>V</span><span>O</span><span>I</span><span>C</span><span>E</span></h1><div class="invoice-meta"><div class="meta-item"><div class="meta-label">Invoice No.</div><div>{INVOICE_ID}</div></div><div class="meta-item"><div class="meta-label">Issue Date</div><div>{MONTH} {ISSUE_DAY}, {YEAR}</div></div><div class="meta-item"><div class="meta-label">Due Date</div><div>{MONTH} {DUE_DAY}, {YEAR}</div></div></div></header><section class="parties"><div class="party"><div class="party-label">From</div><div class="party-name">{FROM_NAME}</div><div class="party-details"><div>{FROM_PHONE}</div><div>{FROM_EMAIL}</div><div>{FROM_ADDRESS}</div></div></div><div class="party"><div class="party-label">Bill To</div><div class="party-name">{CLIENT_NAME}</div><div class="party-details">{CLIENT_DETAILS}</div></div></section><section class="items-section"><div class="items-header"><span class="items-header-label">Description</span><span class="items-header-label">Amount</span></div><div class="item-row"><span class="item-description">{DESCRIPTION}</span><span class="item-amount">{AMOUNT}</span></div></section><div class="bottom-section"><section class="payment-section">{PAYMENT_SECTION}</section><div class="totals"><div class="totals-label">Total</div><div class="totals-value">{TOTAL}</div><div class="currency-note">All amounts in {CURRENCY}</div></div></div></div></body></html>`;

const css = `@page{size:A4;margin:0}*{margin:0;padding:0;box-sizing:border-box}html{width:210mm;height:297mm;background:#fff}body{width:210mm;height:297mm;font-family:'Inter',-apple-system,BlinkMacSystemFont,sans-serif;background:#fff;color:#0a0a0a;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale;position:relative;overflow:hidden}.invoice{width:100%;height:100%;padding:56px;display:flex;flex-direction:column;justify-content:space-between}.invoice-title{font-family:'Inter Tight','Inter',sans-serif;font-size:180px;font-weight:400;line-height:1;color:#0a0a0a;text-transform:uppercase;margin-top:-74px;margin-bottom:80px;display:flex;justify-content:space-between;width:100%}.invoice-meta{display:flex;justify-content:space-between;font-size:13px;font-weight:400;color:#0a0a0a;letter-spacing:0.01em;font-variant-numeric:tabular-nums}.meta-label{font-size:11px;font-weight:600;text-transform:uppercase;letter-spacing:0.2em;color:#525252;margin-bottom:8px}.parties{display:grid;grid-template-columns:1fr 1fr;gap:40px}.party:last-child{justify-self:end}.party-label{font-size:11px;font-weight:600;text-transform:uppercase;letter-spacing:0.2em;color:#525252;margin-bottom:24px}.party-name{font-size:28px;font-weight:600;letter-spacing:-0.02em;margin-bottom:20px;color:#0a0a0a}.party-details{font-size:14px;font-weight:400;line-height:1.8;color:#404040}.items-header{display:flex;justify-content:space-between;padding-bottom:16px;border-bottom:1px solid #e5e5e5;margin-bottom:24px}.items-header-label{font-size:11px;font-weight:600;text-transform:uppercase;letter-spacing:0.2em;color:#525252}.item-row{display:flex;justify-content:space-between;align-items:flex-start}.item-description{font-size:15px;font-weight:400;color:#0a0a0a}.item-amount{font-size:15px;font-weight:500;color:#0a0a0a;font-variant-numeric:tabular-nums}.bottom-section{display:flex;justify-content:space-between;align-items:flex-end}.payment-section{max-width:320px}.payment-label{font-size:11px;font-weight:600;text-transform:uppercase;letter-spacing:0.2em;color:#525252;margin-bottom:20px}.bank-details{font-size:13px;font-weight:400;line-height:1.9;color:#0a0a0a}.bank-details .bank-name{font-weight:500;color:#0a0a0a}.payment-button{display:inline-flex;align-items:center;gap:12px;padding:14px 28px;border:none;border-radius:9999px;background:#0a0a0a;color:#fff!important;font-size:14px;font-weight:500;text-decoration:none;letter-spacing:0.01em}.payment-button .arrow{font-size:18px;line-height:1;color:#fff}.totals{text-align:right}.totals-label{font-size:11px;font-weight:600;text-transform:uppercase;letter-spacing:0.2em;color:#525252;margin-bottom:12px}.totals-value{font-size:44px;font-weight:600;letter-spacing:-0.02em;color:#0a0a0a;margin-bottom:8px;font-variant-numeric:tabular-nums}.currency-note{font-size:12px;font-weight:400;color:#525252}@media print{html,body{width:210mm;height:297mm;-webkit-print-color-adjust:exact;print-color-adjust:exact}}`;

export const defaultTheme: Theme = {
	id: "default",
	name: "Classic",
	html,
	css,
	paymentMethodFields: `<div class="payment-label">{METHOD_LABEL}</div><div class="bank-details">{FIELDS}</div>`,
	paymentMethodLink: `<div class="payment-label">{METHOD_LABEL}</div><a href="{LINK_URL}" class="payment-button"><span>{LINK_TEXT}</span><span class="arrow">→</span></a>`,
	paymentField: `<div>{FIELD_LABEL}: {FIELD_VALUE}</div>`
};
